const fs = require('fs');
const path = require('path');
const PDFDocument = require('pdfkit');

const PDF_DIR = path.join(__dirname, '..', 'public', 'pdfs');
if (!fs.existsSync(PDF_DIR)) fs.mkdirSync(PDF_DIR, { recursive: true });

// Generates a real, downloadable PDF course handout (syllabus + module
// breakdown) for a course and writes it to /server/public/pdfs/<id>.pdf.
// Returns the relative URL path to serve it at.
function generateCourseHandout(course) {
  const fileName = `${course.id}.pdf`;
  const filePath = path.join(PDF_DIR, fileName);
  const doc = new PDFDocument({ margin: 50 });
  doc.pipe(fs.createWriteStream(filePath));

  doc.fontSize(22).fillColor('#1e293b').text(course.name, { align: 'left' });
  doc.moveDown(0.3);
  doc.fontSize(11).fillColor('#64748b')
    .text(`Instructor: ${course.instructor}    |    Duration: ${course.duration} weeks    |    Category: ${course.category}`);
  doc.moveDown(1);
  doc.strokeColor('#e2e8f0').moveTo(50, doc.y).lineTo(545, doc.y).stroke();
  doc.moveDown(1);

  doc.fontSize(14).fillColor('#0f172a').text('Course Description', { underline: true });
  doc.moveDown(0.3);
  doc.fontSize(11).fillColor('#334155').text(course.description, { align: 'justify' });
  doc.moveDown(1);

  doc.fontSize(14).fillColor('#0f172a').text('Module-by-Module Syllabus', { underline: true });
  doc.moveDown(0.5);

  const modules = course.modules || [];
  modules.forEach((m, i) => {
    doc.fontSize(12).fillColor('#1d4ed8').text(`${i + 1}. ${m.title}`);
    doc.fontSize(10.5).fillColor('#334155').text(m.content || '', { indent: 15 });
    if (m.materials && m.materials.length) {
      m.materials.forEach(mat => {
        doc.fontSize(9.5).fillColor('#0891b2').text(`• ${mat.title}: ${mat.url}`, { indent: 15 });
      });
    }
    doc.moveDown(0.6);
  });

  doc.moveDown(1);
  doc.fontSize(9).fillColor('#94a3b8')
    .text('Generated by Coursepath — Student Course Management & Learning Progress Tracking System.', { align: 'center' });

  doc.end();
  return `/pdfs/${fileName}`;
}

module.exports = { generateCourseHandout };
